### ISSUE TITLE
No output file

### ISSUE THREAD

**Issue by kevglynn** [JasonDixonGit/MyTwitterScraper#1]
The output-to-csv part of the application seems a bit buggy.
1. Can't name file
2. Can't click save... that being said, when I click cancel, the dialogue tells me the file was generated.
3. No output file created

(using OS X 10.11.3)

**Comment by JasonDixonGit** [comment]
Thanks for at least emailing me before you open an issue. My email and contact info are plastered all over the web page for this software. The output to csv "thing" is Java's save dialogue, not mine. There's nothing custom written there. Your OS doesn't matter as much as the version of Java you're using. What version of Java are you running?

**Comment by invalidjson** [comment]
Ok, I'll leave this open for a week to try to help you with the software, then I'm closing it. I get a few emails a week from users asking one question or another, and I usually drop what I'm doing to help them configure or work with this FREE software. As such, if you have a concern, an email would have, and still is, the appropriate manner in which to seek help. I think my phone number is even in my contact info. Github issues are for bugs you've found. I tried to replicate your bug on OSX10 and could not, so I would like to figure out what is going wrong in your particular case, and so that you can successfully use the software. If you've found a legitimate bug, feel free to perform some static analysis on the class that handles the save dialog operation, and either fix it and make a pull request, or submit it to me and I will handle the bug fix. The save dialog is Java's native method, not mine. Also, please make sure you're running Java 8. In the future, if you need technical support, please reach out to the developer instead of opening a public issue where the code base is stored. Please email me at jason.github@gmail.com and let's figure out what is causing the issue on your machine? I'll leave this open for 7 days, or until I either hear from you here or via email. Thanks

**Comment by invalidjson** [comment]
Ok, I'm closing this issue as user error as the user who reported this has not responded within the last 10 days. With currently over 3000 downloads this has not been reported before, but if anyone experiences this issue again please feel free to email me and we can work through what might be going wrong.
